name: Build workflow
on: push
jobs:
  gradle:
    name: Gradle build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Add Gradle Credentials
        run: |
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} > ~/.gradle/gradle.properties"
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_KEY }} >> ~/.gradle/gradle.properties"
        with:
          arguments: addCredentials --key gradle.publish.key --value ${{ secrets.GRADLE_PUBLISH_KEY }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Build project with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
