name: Continuous Integration workflow
on: push
jobs:
  gradle:
    name: Gradle build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
